In [1]:
import pandas as pd
import numpy as np

In [2]:
articles = pd.read_csv(r"C:\Users\Parsa\Downloads\articles.csv")
profs = pd.read_csv(r"C:\Users\Parsa\Downloads\professors.csv")

In [3]:
uni = pd.read_csv(r"C:\Users\Parsa\Downloads\universities.csv")

In [6]:
uni_gnm_list = uni[uni['GNM'] == 1]['University'].to_list()
uni_gnm_list

['University of Tehran',
 'Sharif University of Technology',
 'Ferdowsi University of Mashhad',
 'Amirkabir University of Technology',
 'Shahid Beheshti University',
 'University of Isfahan',
 'Tarbiat Modares University',
 'Shiraz University',
 'Isfahan University of Technology',
 'University of Tabriz',
 'Iran University of Science and Technology',
 'Urmia University',
 'K. N. Toosi University of Technology',
 'Shahid Chamran University of Ahvaz',
 'Zanjan University',
 "Allameh Tabataba'i University",
 'Alzahra University',
 'The University of Guilan',
 'Semnan University',
 'Shahrekord University',
 'University of Social Welfare and Rehabilitation Sciences',
 'Yazd University',
 'University of Kashan',
 'Bu-Ali Sina University',
 'Razi University',
 'University of Sistan and Baluchestan',
 'Imam Khomeini International University',
 'University of Birjand',
 'University of Kurdistan',
 'Persian Gulf University',
 'Shahid Bahonar University of Kerman',
 'Arak University',
 'Kharazmi University',
 'Sahand University of Technology',
 'Imam Sadiq University',
 'Shahid Rajaee Teacher Training University',
 'University of Mazandaran',
 'Shahrood University of Technology',
 'University of Mohaghegh Ardabili',
 'University of Qom',
 'Institute for Advanced Studies in Basic Sciences',
 'Ilam University',
 'Petroleum University of Technology',
 'Shahed University',
 'Azarbaijan Shahid Madani University',
 'Golestan University',
 'Babol Noshirvani University of Technology',
 'Hakim Sabzevari University',
 'Damghan University',
 'ValiAsr University of Rafsanjan',
 'Al Mustafa International University',
 'Lorestan University',
 'University of Maragheh',
 'Iran Polymer and Petrochemical Institute',
 'Hormozgan University',
 'University of Zabol',
 'Malayer University',
 'Shiraz University of Technology',
 'Urmia University of Technology',
 'Ardakan University',
 'Qom University of Technology',
 'Kermanshah University of Technology',
 'Graduate University of Advanced Technology',
 'Mazandaran University of Science and Technology']

In [10]:
profs['cited_by_all'] = pd.to_numeric(profs['cited_by_all'], errors='coerce')
del_prof = profs[profs["cited_by_all"] < 100]
del_prof_ids_1 = set(del_prof.id.to_list())

In [11]:
del_prof

,id,name,university,user_id,affiliation,v_email_at,interests,cited_by_all,cited_by_since_2020,h_index_all,h_index_since_2020,i10_index_all,i10_index_since_2020,yearly_data
44,44,Seyed Ali Hoseini,University of Tehran,-IpMEz0AAAAJ,University of Tehran,ut.ac.ir,"Semiconductor Devices, Biosensors, Li Ion battery",40.0,39,1,1,1,1,"{'2019': 1, '2020': 5, '2021': 11, '2022': 11,..."
79,79,Shams Mohajerzadeh,University of Tehran,lakmLYkAAAAJ,"Professor of Electrical Engineering, Universit...",ut.ac.ir,NaN,0.0,0,0,0,0,0,No data available
89,89,Mohammad Jamali,University of Tehran,mQ7UrY0AAAAJ,"Dr. Jurisprudence and comparative law, Univers...",ut.ac.ir,"Principles and rules of law, Jurisprudence Eba...",8.0,3,2,1,0,0,"{'2016': 2, '2017': 1, '2018': 1, '2019': 2, '..."
93,93,Nasser Mehrdadi,University of Tehran,fzQle0cAAAAJ,"Department of environmental engineering, Unive...",ut.ac.ir,"Environmental engineering, Wastewater treatment",0.0,0,0,0,0,0,No data available
144,144,Milad Sadeghzadeh,University of Tehran,I6nhK8UAAAAJ,"M.Sc. Energy Systems Engineering, University o...",ut.ac.ir,"Thermodynamics, Renewable Energy, Multi-genera...",0.0,0,0,0,0,0,No data available
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49873,50232,Mehran Gharye Mirzaei,K. N. Toosi University of Technology,cZoCKlMAAAAJ,KNToosi university,alumni.kntu.ac.ir,"Multi-objective optimization, Robust Optimizat...",42.0,42,3,3,2,2,"{'2022': 2, '2023': 4, '2024': 35}"
49874,50233,Abdollah Sharifi,K. N. Toosi University of Technology,RHS0uGoAAAAJ,"Industrial Engineering Ph.D., KN Toosi Univers...",email.kntu.ac.ir,"Simulation, Evolutionary Algorithms, Supply Ch...",40.0,19,1,1,1,1,"{'2014': 1, '2015': 3, '2016': 2, '2017': 2, '..."
49875,50234,Hamed Khanmirza,K. N. Toosi University of Technology,muaBmQQAAAAJ,KN Toosi University of Technology,kntu.ac.ir,"Distributed Systems, IoT, Computer Networks, SDN",39.0,18,4,3,0,0,"{'2005': 1, '2006': 1, '2007': 2, '2008': 1, '..."
49876,50235,Ali Aminzadeh,K. N. Toosi University of Technology,hdzM2mwAAAAJ,KN Toosi University of Technology,email.kntu.ac.ir,"Formal Verification, Large-scale Networks, Dat...",39.0,30,3,3,1,1,"{'2018': 3, '2019': 6, '2020': 2, '2021': 4, '..."
49877,50236,Farzad Yousefian,K. N. Toosi University of Technology,dVxO98UAAAAJ,"Master student, KN Toosi University of Technology",email.kntu.ac.ir,"Concrete, Pavement, Fracture Mechanics, Asphalt",39.0,38,1,1,1,1,"{'2021': 2, '2022': 13, '2023': 12, '2024': 11}"

In [12]:
del_prof = profs[~ profs["university"].isin(uni_gnm_list)]
prof = profs[profs["university"].isin(uni_gnm_list)]


prof = prof[prof["cited_by_all"] >= 100]
prof

,id,name,university,user_id,affiliation,v_email_at,interests,cited_by_all,cited_by_since_2020,h_index_all,h_index_since_2020,i10_index_all,i10_index_since_2020,yearly_data
0,0,Ali Fahim,University of Tehran,_C4Iif8AAAAJ,"Assistant Professor of Physics, University of ...",ut.ac.ir,"Elementary Particle Physics, Physics of Comple...",136197.0,33327,164,76,303,248,"{'2010': 526, '2011': 2426, '2012': 5812, '201..."
1,1,Mohammad Reza Ganjali,University of Tehran,IJ3XCecAAAAJ,"Professor of Analytical Chemistry, University ...",khayam.ut.ac.ir,"Sensor and biosensor, Elctroanalytical Chemist...",58570.0,23375,111,67,1070,580,"{'2002': 200, '2003': 286, '2004': 278, '2005'..."
2,2,Norouzi Parviz,University of Tehran,usWI6hMAAAAJ,"Professor of Electrochemistry, Collage of Scie...",ut.ac.ir,"Electrochemistry, Electrochemical Sensors, Bio...",27458.0,6966,84,37,532,203,"{'2006': 211, '2007': 605, '2008': 874, '2009'..."
3,3,Reza Tavakkoli-Moghaddam,University of Tehran,gqVUx4cAAAAJ,Distinguished Professor of Industrial Engineer...,ut.ac.ir,"Facilities design, Supply chain, Scheduling, T...",30636.0,17133,87,59,569,424,"{'2008': 128, '2009': 235, '2010': 315, '2011'..."
4,4,Ali Akbar Moosavi-Movahedi,University of Tehran,sZysKwIAAAAJ,University of Tehran,ut.ac.ir,Biophysical Chemistry,20464.0,8628,70,43,447,212,"{'2002': 116, '2003': 153, '2004': 187, '2005'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49937,50932,n rahemi,Iran University of Science and Technology,AWT3WagAAAAJ,"Assistant Professor, Iran University of Scienc...",iust.ac.ir,NaN,115.0,87,7,6,4,3,"{'2015': 1, '2016': 7, '2017': 6, '2018': 8, '..."
49938,50944,Salman Saremian,Iran University of Science and Technology,veB5yggAAAAJ,"PhD, Iran University of Science and Technology",mecheng.iust.ac.ir,"Fluid Dynamic, Energy, Turbomachines, Turbulen...",109.0,96,4,4,2,2,"{'2019': 12, '2020': 17, '2021': 13, '2022': 1..."
49939,50947,Nasim Amiri Ramsheh,Iran University of Science and Technology,gYG69ocAAAAJ,Catalysts and Organic Synthesis Research Labor...,chem.iust.ac.ir,"Green Chemistry, Natural Polymer, Catalysis, E...",108.0,108,6,6,5,5,"{'2023': 12, '2024': 90}"
49940,50957,Mahdi Asadi,Iran University of Science and Technology,t5Du678AAAAJ,"Master Graduate of Mechanical Engineering, Ira...",alumni.iust.ac.ir,"Energy Systems, Energy Harvesting, Renewable E...",106.0,106,6,6,2,2,"{'2023': 12, '2024': 82}"
49941,50962,Arsalan Ajdani,Iran University of Science and Technology,bJXabpcAAAAJ,"Ph.D., Iran University of Science and Technology",alumni.iust.ac.ir,"Fracture mechanics, adhesive joints, cohesive ...",104.0,104,4,4,4,4,"{'2020': 10, '2021': 18, '2022': 17, '2023': 3..."

In [13]:
highly_cited_prof_id_list = prof['id']

In [14]:
highly_cited_prof_id_list

0            0
1            1
2            2
3            3
4            4
         ...
49937    50932
49938    50944
49939    50947
49940    50957
49941    50962
Name: id, Length: 18632, dtype: int64

In [21]:
articles[(articles['year'] >= 1399) & (articles['year'] <= 1404)]

,id,title,GS_link,year,cite,main_authors,more_info,link_ids
49535,49914,Continuous and controlled production of dexame...,/citations?view_op=view_citation&hl=en&user=C1...,1399.0,0,P Zahedi- M Tabatabaei- M Fathipour- A Sohrabi,Journal of Applied Research in Chemistry 14 (2...,187
105252,106275,طرح های کوچک حیاتی، خلاصه ای از کارهای جین جیک...,/citations?view_op=view_citation&hl=en&user=1M...,1399.0,0,مترجم: سعید زنگنه شهرکی‎,انتشارات دانشگاه تهران- 1399‎,735
122450,123797,شبکه های اجتماعی علمی: مبانی، مفاهیم و کاربردها‎,/citations?view_op=view_citation&hl=en&user=DE...,1400.0,0,علی شرفی،علیرضا نوروزی، محمدرضا اسمعیلی گیوی‎,نشر پاچار- 1400‎,1140
122451,123799,Big data functions in integrated policy making...,/citations?view_op=view_citation&hl=en&user=DE...,1400.0,0,ME Givi,مقالات دومین همایش ملی حکمرانی اسلامی- 1400‎,1140
122452,123800,ارائه الگوي پویای سيستمي برای تأثیرگذاری اجتما...,/citations?view_op=view_citation&hl=en&user=DE...,1399.0,0,ME Givi,همایش ملی کارکردهای اجتماعی کتابخانه های عمومی...,1140
...,...,...,...,...,...,...,...,...
1418662,1450079,پیش بینی رابطه اخلاق و محیط کسب وکار با توسعه ...,/citations?view_op=view_citation&hl=en&user=m_...,1399.0,0,سعید کیان پور*، علی فلاحتی، مرتضی مرادی، محمد ...,اخلاق در علوم و فناوری 15 (2)- ۹۹-۹۳- 1399‎,48735
1425656,1457334,ارزیابی مطلوبیت زیستگاه کفتار(Hyaena hyaena) ب...,/citations?view_op=view_citation&hl=en&user=kM...,1399.0,0,مریم مروتی، مهدیه ابراهیمی، فاطمه بهادری امجز‎,محیط زیست جانوری 4- 1-9- 1399‎,49091
1425657,1457335,ارزیابی آسیب‌پذیری آب زیرزمینی دشت نکارود با ...,/citations?view_op=view_citation&hl=en&user=kM...,1399.0,0,سیده عالمه صباغ،مریم مروتی،مریم پناهنده، مهدی ...,پژوهش آب ایران 1 (14)- 141-152- 1399‎,49091
1426485,1458224,ویژگیهای روانسنجی مقیاس منبع کنترل تحصیلی در د...,/citations?view_op=view_citation&hl=en&user=mh...,1399.0,0,آریانپور، حمیدرضا؛ رضاپور میرصالح، یاسر‎,آموزش و ارزشیابی 13- 127-147- 1399‎,49139
1428841,1460670,طراحی یک کنترل‌کننده هوشمند اضافه بار جهت استف...,/citations?view_op=view_citation&hl=en&user=Rm...,1401.0,0,مهدی خزائی‎,نشریه مهندسی برق و مهندسی کامپيوتر ايران 20 (2...,49265

In [23]:
all_ids = (
    articles
      .loc[lambda df: df['year'].between(1399, 1404), 'link_ids']
      .str.split('-')
      .explode()
      .astype(int)
      .tolist()
)
len(all_ids)

501

In [24]:
prof_in_shamsi_year = prof[prof['id'].isin(all_ids)]

In [25]:
prof_in_shamsi_year

,id,name,university,user_id,affiliation,v_email_at,interests,cited_by_all,cited_by_since_2020,h_index_all,h_index_since_2020,i10_index_all,i10_index_since_2020,yearly_data
187,187,Payam Zahedi,University of Tehran,C1HNNU0AAAAJ,"Associate Prof. of Polymer Eng. & Sci., Univer...",ut.ac.ir,"Nanofibers, Molecular Imprinted Polymers, Micr...",3275.0,1970,27,22,50,46,"{'2011': 25, '2012': 48, '2013': 85, '2014': 9..."
733,735,Saeed Zanganeh Shahraki,University of Tehran,1MT4pN4AAAAJ,"Associate Professor, University of Tehran.",ut.ac.ir,"urban smart growth, urban sprawl",997.0,673,14,12,18,15,"{'2011': 8, '2012': 16, '2013': 16, '2014': 37..."
1137,1140,ME G,University of Tehran,DEvptEwAAAAJ,Associate prof; Department of Public Administr...,ut.ac.ir,"Public Administration, Governance, Information...",424.0,263,11,11,12,11,"{'2011': 7, '2012': 15, '2013': 12, '2014': 14..."
1247,1251,Abolghasem Goorabi,University of Tehran,FqvNA5IAAAAJ,"Associate Professor, Faculty of Geography, Uni...",ut.ac.ir,"Geomorphology-Paleoseismology, Quaternary Land...",369.0,236,8,6,7,4,"{'2008': 2, '2009': 1, '2010': 2, '2011': 5, '..."
1467,1471,Ali Reza Radkhah,University of Tehran,mPCZS6MAAAAJ,"Fisheries Dept., Faculty of Natural Resources,...",ut.ac.ir,"Aquatic Ecology, Fish Biology, Fish Ecology, I...",282.0,213,7,7,5,5,"{'2015': 4, '2016': 7, '2017': 9, '2018': 19, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47798,47831,mohammad hossein azadi,Lorestan University,wMcb-MIAAAAJ,"phd student , Department of Management and Eco...",fc.lu.ac.ir,مدیریت_ اعداد فازی_ اعداد فازی نوع ۲_ منابع\xa0…,224.0,200,4,4,3,3,"{'2017': 2, '2018': 7, '2019': 14, '2020': 22,..."
48392,48425,Somayeh Dianat,Hormozgan University,hRTePZwAAAAJ,"Department of Chemistry, Faculty of Sciences, ...",hormozgan.ac.ir,"catalysis, electrocatalysis, electrochemistry,...",297.0,227,10,9,10,9,"{'2014': 4, '2015': 9, '2016': 6, '2017': 10, ..."
48418,48451,Mahdi Mohammad Mahdizadeh,Hormozgan University,nNH4KnMAAAAJ,University of Hormozgan,hormozgan.ac.ir,Physical Oceanography,152.0,122,6,5,4,3,"{'2010': 1, '2011': 1, '2012': 1, '2013': 5, '..."
48621,48654,Farshid Mirzaee (ORCID: 0000-0002-1429-2548),Malayer University,yz0HEkYAAAAJ,"Professor of Applied Mathematics, Malayer Univ...",malayeru.ac.ir,"Numerical Analysis, Integral Equations, Stocha...",4268.0,3109,40,34,107,93,"{'2009': 12, '2010': 19, '2011': 34, '2012': 4..."
49057,49091,Maryam Morovati,Ardakan University,kMXYo84AAAAJ,Associate Professor in Environmental Sceince....,ardakan.ac.ir,"Environmental Sceince, Biodiversity, Environme...",662.0,625,11,10,12,11,"{'2013': 4, '2014': 4, '2015': 4, '2016': 2, '..."